import os
env = Environment(ENV = {'PATH' : os.environ['PATH'],
                         'TERM' : os.environ['TERM'],
                         'HOME' : os.environ['HOME']})

graphene = os.environ['GRAPHENE_ROOT']
env['CCFLAGS'] += ['-g', '-Wall', '-std=c++11', '-O2', '-D GL_GLEXT_PROTOTYPES', '-D USE_BOOST_RANDOM', '-D NDEBUG', '-Wno-unknown-pragmas', '-Wno-deprecated-declarations', '-Wno-strict-aliasing', '-Wno-attributes', '-Wno-unused-local-typedefs']
env['CPPPATH'] = ['.','/usr/local/include/commons', "/usr/include/eigen3", graphene]
env['LIBPATH'] = ['/usr/local/lib/commons', graphene]
env['LIBS']    = ['IO', 'RNG', 'boost_system','boost_filesystem','GLEW', 'glut', 'graphene']
env['SHLIBPREFIX'] = ''

env.SharedLibrary('visSkeleton', ['visSkeleton.cpp','Skeleton.cpp'])
