import os
env = Environment(ENV = {'PATH' : os.environ['PATH'],
                         'TERM' : os.environ['TERM'],
                         'HOME' : os.environ['HOME']})

graphene = os.environ['GRAPHENE_ROOT']
commons = os.environ['COMMONS']
env['CCFLAGS'] += ['-g', '-Wall', '-fPIC', '-std=c++11', '-O2', '-D GL_GLEXT_PROTOTYPES', '-D USE_BOOST_RANDOM', '-D NDEBUG', '-Wno-unknown-pragmas', '-Wno-deprecated-declarations', '-Wno-strict-aliasing', '-Wno-attributes', '-Wno-unused-local-typedefs']
env['CPPPATH'] = ['.', '/usr/include/eigen3', graphene, commons]
env['LIBPATH'] = [graphene]
env['LIBS']    = ['boost_system','boost_filesystem','GLEW', 'glut', 'graphene']

env.Library('SelectBase', ['SelectBase.cpp'])
