import os
env = Environment(ENV = {'PATH' : os.environ['PATH'],
                         'TERM' : os.environ['TERM'],
                         'HOME' : os.environ['HOME']})

env['CCFLAGS'] += ['-g', '-Wall', '-std=c++11', '-O2', '-D GL_GLEXT_PROTOTYPES', '-D USE_BOOST_RANDOM', '-D NDEBUG', '-Wno-unknown-pragmas', '-Wno-deprecated-declarations', '-Wno-strict-aliasing', '-Wno-attributes', '-Wno-unused-local-typedefs']
env['CPPPATH'] = ['.', '/usr/include/eigen3', '/usr/include/graphene']
env['LIBPATH'] = ['/usr/lib/OpenMesh']
env['LIBS']    = ['boost_system','boost_filesystem','GLEW', 'glut', 'Graphene', 'OpenMeshCore']
env['SHLIBPREFIX'] = ''

env.SharedLibrary('visMeshRender', ['visMeshRender.cpp','MeshRender.cpp'])
